### ISSUE TITLE
No such module 'SwiftyUserDefault'

### ISSUE THREAD

**Issue by FlorentAnders** [TwidereProject/Twidere-iOS#2]
When trying to build on Sierra, I get a "No such module 'SwiftyUserDefault'". Do you know how to fix that?

**Comment by mariotaku** [comment]
Maybe pod install first? I'll come back to this project soon

**Comment by FlorentAnders** [comment]
I made it, do I need to something special after pod install in Xcode itself?:)

**Comment by FlorentAnders** [comment]
I opened the wrong workspace. So sorry!
